/*
 * Recipe Rex API
 * Rest services for Recipe Rex web application. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Cookbook
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-13T06:28:01.512Z")
public class Cookbook {
  @SerializedName("userId")
  private Long userId = null;

  @SerializedName("recipeId")
  private List<Long> recipeId = new ArrayList<Long>();

  public Cookbook userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public Cookbook recipeId(List<Long> recipeId) {
    this.recipeId = recipeId;
    return this;
  }

  public Cookbook addRecipeIdItem(Long recipeIdItem) {
    this.recipeId.add(recipeIdItem);
    return this;
  }

   /**
   * Get recipeId
   * @return recipeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getRecipeId() {
    return recipeId;
  }

  public void setRecipeId(List<Long> recipeId) {
    this.recipeId = recipeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cookbook cookbook = (Cookbook) o;
    return Objects.equals(this.userId, cookbook.userId) &&
        Objects.equals(this.recipeId, cookbook.recipeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, recipeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cookbook {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    recipeId: ").append(toIndentedString(recipeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

